=head1 Perliki

A simple wiki engine.

=head1 Installation

    # Clone contrib libraries
    $ git submodule update --init

    # Install dependencies
    $ cpanm --installdeps . -L perl5/

    # or with carton
    $ carton install

    # Copy configs
    $ cp configs/acl.yml.example configs/acl.yml
    $ cp configs/config.yml.example configs/config.yml

    # Create database
    $ sqlite3 wiki.db < schema/SQLite.sql

    # Start the server
    $ plackup -Mlocal::lib=perl5

    # or with carton
    $ carton exec -- plackup
